module CertificatesHelper
  # Inline SVG QR pointing back at the app — the certificate's "verify" mark. The
  # markup is generated by rqrcode from a server-built URL (no user input), so it's
  # safe to mark HTML-safe.
  def certificate_qr_code(url)
    svg = RQRCode::QRCode.new(url).as_svg(
      viewbox: true,
      use_path: true,
      color: "111111",
      shape_rendering: "crispEdges"
    )
    tag.div(svg.html_safe, class: "w-20 h-20", role: "img", aria: { label: "Verification QR code" })
  end
end
